import type { Context, Config } from "@netlify/functions";
import * as XLSX from "xlsx";
import { takeExport } from "./_shared/export-store.mts";
import { isAuthorized, loginRedirect } from "./_shared/auth.mts";

function addSheet(wb:XLSX.WorkBook,name:string,rows:Record<string,any>[],widths:number[]){const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{提示:"无数据"}]);ws["!cols"]=widths.map(wch=>({wch}));ws["!autofilter"]=ws["!ref"]?{ref:ws["!ref"]}:undefined;XLSX.utils.book_append_sheet(wb,ws,name);return ws}
function formatOverlay(ws:XLSX.WorkSheet,rows:Record<string,any>[]){if(!rows.length)return;const headers=Object.keys(rows[0]),rateCol=headers.indexOf("费率"),moneyNames=new Set(["CP余额","SO","预测SO","毛承载","TTS已占用","净承载","预测承载","计入可见承载"]),moneyCols=headers.map((h,i)=>moneyNames.has(h)?i:-1).filter(i=>i>=0);for(let r=1;r<=rows.length;r++){if(rateCol>=0){const cell=ws[XLSX.utils.encode_cell({r,c:rateCol})];if(cell&&typeof cell.v==="number")cell.z="0.00%"}for(const c of moneyCols){const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell&&typeof cell.v==="number")cell.z="#,##0.00"}}ws["!freeze"]={xSplit:0,ySplit:1,topLeftCell:"A2",activePane:"bottomLeft",state:"frozen"} as any}

export default async(req:Request,context:Context)=>{if(!isAuthorized(req))return loginRedirect();if(req.method!=="GET")return new Response("Method Not Allowed",{status:405});const token=new URL(req.url).searchParams.get("token")||"";if(!/^[0-9a-f-]{36}$/i.test(token))return new Response("无效下载令牌",{status:400});const payload:any=await takeExport(context,token);if(!payload)return new Response("下载结果已失效或已下载，请重新上传四个文件生成。",{status:410,headers:{"content-type":"text/plain;charset=utf-8"}});const wb=XLSX.utils.book_new(),overlay=Array.isArray(payload.overlayRows)?payload.overlayRows:[],summary=Array.isArray(payload.summaryRows)?payload.summaryRows:[],fingerprints=Array.isArray(payload.fingerprintRows)?payload.fingerprintRows:[],rules=Array.isArray(payload.ruleRows)?payload.ruleRows:[];const overlayWs=addSheet(wb,"Overlay明细",overlay,[16,24,12,15,28,12,14,34,22,16,10,14,14,10,14,14,14,14,14,42]);formatOverlay(overlayWs,overlay);addSheet(wb,"客户CP汇总",summary,[28,16,30,14,14,14,14,14,14,14,12]);addSheet(wb,"材料指纹",fingerprints,[14,42,12,68,20,20]);addSheet(wb,"规则说明",rules,[18,80]);wb.Props={Title:"费用规划助手分析结果",Subject:"区域自主 Overlay 输入",Author:"费用规划助手",Comments:`生成时间 ${payload.generatedAt||""}；版本 ${payload.version||""}`};const output=XLSX.write(wb,{type:"buffer",bookType:"xlsx",compression:true}),filename=`费用规划助手_分析结果_${new Date().toISOString().slice(0,10).replace(/-/g,"")}.xlsx`;return new Response(output,{headers:{"content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(filename)}`,"cache-control":"no-store"}})};
export const config:Config={path:"/download-analysis2"};
