const IDS=['nav','title','msg','sysS','sysE','cpSel','capSel','planCP','rateOverride','clientOverride','excludeOverride','cpRows','minPit','roundUnit','clientRows','bucketRows','planClient','planAmt','histS','histE','futureM','planRows','outMsg','outRows','kSO','kTTS','kCP','kSKU'];
IDS.forEach(id=>window[id]=document.getElementById(id));
const NAV=[['files','数据更新'],['cp','CP范围'],['cap','承载/拍板'],['plan','计划展开'],['out','模板输出']];
const F={BI:null,TTS:null,CP:null,CAT:null};
let D={so:[],tts:[],cps:[],catalog:new Map(),profiles:new Map()},state={cp:'',ov:{},approved:{},plans:[]};
function init(){nav.innerHTML=NAV.map((x,i)=>`<button class="${i?'':'active'}" onclick="go('${x[0]}',this)">${x[1]}</button>`).join('');let now=new Date(),y=now.getFullYear(),nm=now.getMonth()+2;if(nm>12){nm-=12;y++}let m=String(nm).padStart(2,'0');sysS.value=`${y}-${m}-01`;sysE.value=`${y}-${m}-${new Date(y,nm,0).getDate()}`;loadState();if(typeof XLSX==='undefined')setMsg('页面脚本已运行，但 Excel 解析组件没有加载。说明公司网络拦截了 Excel 组件地址。','warn');else setMsg('运行引擎已加载。选择四个文件后点击“自动解析并计算”。','ok')}
function go(id,b){document.querySelectorAll('.sec').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');title.textContent=NAV.find(x=>x[0]===id)[1];render()}
function pick(t,e){F[t]=e.target.files[0]||null;document.getElementById('box'+t).classList.toggle('ok',!!F[t])}
function n(v){let x=parseFloat(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0}function s(v){return String(v??'').trim()}function list(v){return s(v).split(/[,，;]/).map(x=>x.trim()).filter(Boolean)}function money(v){return '¥'+n(v).toLocaleString('zh-CN',{maximumFractionDigits:2})}function pct(v){return (n(v)*100).toFixed(1)+'%'}function ym(v){if(/^\d{6}$/.test(s(v)))return s(v);let d=date(v);return d?d.getFullYear()+String(d.getMonth()+1).padStart(2,'0'):''}function date(v){if(v instanceof Date)return v;if(typeof v==='number'&&v>30000)return new Date(Date.UTC(1899,11,30)+v*86400000);let d=new Date(v);return isNaN(d)?null:d}function fd(v){let d=date(v);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:''}function mend(m){return fd(new Date(+m.slice(0,4),+m.slice(4,6),0))}function clientName(x){return s(x).replace(/(有限责任公司|股份有限公司|有限公司)$/,'').trim()}
async function wb(file){let a=await file.arrayBuffer();return XLSX.read(a,{type:'array',cellDates:true})}
function rows(w,name){let sh=w.Sheets[name]||w.Sheets[w.SheetNames.find(x=>x.includes(name))]||w.Sheets[w.SheetNames[0]];return XLSX.utils.sheet_to_json(sh,{header:1,raw:true,defval:''})}
function hi(r,req){for(let i=0;i<Math.min(r.length,40);i++){let a=r[i].map(s);if(req.every(x=>a.includes(x)))return i}return-1}
function obj(h,r){let o={};h.forEach((x,i)=>{if(s(x))o[s(x)]=r[i]});return o}
async function analyze(){if(typeof XLSX==='undefined'){setMsg('按钮已响应，但 Excel 解析组件未加载。','warn');return}if(!F.BI||!F.TTS||!F.CP){setMsg('BI、TTS、CP预算是必需文件。','warn');return}setMsg('按钮已响应，正在本地解析 Excel…','');try{let [b,t,c,p]=await Promise.all([wb(F.BI),wb(F.TTS),wb(F.CP),F.CAT?wb(F.CAT):null]);parseBI(b);parseTTS(t);parseCP(c);parseCAT(p,b);buildProfiles();if(!state.cp)state.cp=D.cps[0]?.id||'';render();setMsg(`完成：SO桶 ${D.so.length}，TTS ${D.tts.length}，CP ${D.cps.length}，目录 ${D.catalog.size}。`,'ok')}catch(e){console.error(e);setMsg('解析失败：'+e.message,'warn')}}
function setMsg(x,k){msg.className='msg '+(k||'');msg.textContent=x}
function parseBI(w){let r=rows(w,'BI-SO(折扣)'),i=-1;for(let k=0;k<r.length;k++)if(s(r[k][0])==='Outlet Channel'&&s(r[k][1])==='Customer Code'){i=k;break}D.so=[];if(i<0)throw new Error('BI 中未找到 BI-SO(折扣) 标准表头');let h=r[i],mc=[];h.forEach((x,j)=>{if(/^\d{6}$/.test(s(x)))mc.push([j,s(x)])});for(let k=i+1;k<r.length;k++){let x=r[k],code=s(x[1]);if(!code||code.includes('汇总')||s(x[0])==='总计')continue;for(let [j,m]of mc){let v=n(x[j]);if(!v)continue;D.so.push({channel:s(x[0]),code,client:clientName(x[2]),name:s(x[2]),brand:s(x[3]),brandName:s(x[4]),sku:s(x[7]),skuName:s(x[8]),month:m,so:v*1000})}}}
function parseTTS(w){let r=rows(w,'PPCenturyBigTable'),i=hi(r,['PPCode','Distributor Code','Activity Code in Cycle Plan','Total Budget']);D.tts=[];if(i<0)throw new Error('TTS 中未找到 PPCenturyBigTable 标准表头');let h=r[i];for(let k=i+1;k<r.length;k++){let o=obj(h,r[k]),cp=s(o['Activity Code in Cycle Plan']);if(!cp)continue;let st=s(o.Status);if(/退|拒|取消|删除/.test(st))continue;let amt=n(o.CGOccupancyAmount||o['CGOccupancyAmount']||o['Total Budget']);if(amt<=0)continue;D.tts.push({cp,code:s(o['Distributor Code']),client:clientName(o['Distributor Name']),name:s(o['Distributor Name']),city:s(o.City),channel:s(o.Channel),sku:s(o['Product Code']),amount:amt,start:fd(o.RemarkStartDate||o['Promotion Start Date']),end:fd(o.RemarkEndDate||o['Promotion End Date'])})}}
function rates(x){return [...new Set((s(x).match(/(\d+(?:\.\d+)?)\s*%/g)||[]).map(z=>parseFloat(z)/100))]}
function parseCP(w){let r=rows(w,'CPCenturyBigTableByCGAmount'),i=hi(r,['Activity Code','Activity Start Date','Activity End Date','Balance Amount']);D.cps=[];if(i<0)throw new Error('CP预算中未找到标准表头');let h=r[i];for(let k=i+1;k<r.length;k++){let o=obj(h,r[k]),bal=n(o['Balance Amount']);if(!o['Activity Code']||bal<=0)continue;let mech=s(o['Activity Mechanism']);D.cps.push({id:s(o['Activity Code']),name:s(o['Activity Description']),start:fd(o['Activity Start Date']),end:fd(o['Activity End Date']),sm:ym(o['Activity Start Date']),em:ym(o['Activity End Date']),budget:bal,mg1:list(o.MG1),sub:list(o.SubChannel),mechanism:mech,rates:rates(mech),exclude:/不可核销|排除|除外/.test(mech)?(mech.match(/\b\d{8}\b/g)||[]):[]})}}
function parseCAT(p,b){D.catalog=new Map();let r=p?rows(p,'奶品'):rows(b,'产品目录'),i=-1;for(let k=0;k<Math.min(r.length,30);k++){let a=r[k].map(s);if(a.includes('产品编码')||a.includes('SKU')){i=k;break}}if(i<0)return;let h=r[i];for(let k=i+1;k<r.length;k++){let o=obj(h,r[k]),sku=s(o['产品编码']||o.SKU);if(!sku)continue;D.catalog.set(sku,{name:s(o['产品名称']||o['SKU Name CN']),nps:n(o['NPS\n未税箱价']||o['NPS 未税箱价']||o.Price),brand:s(o.Brand),brandName:s(o['Brand Name'])})}}
function buildProfiles(){D.profiles=new Map();for(let t of D.tts)if(!D.profiles.has(t.code))D.profiles.set(t.code,{city:t.city,name:t.name})}
function ov(cp){return state.ov[cp.id]||{}}function rate(cp){return n(ov(cp).rate)||(cp.rates.length===1?cp.rates[0]:0)}function allowed(cp,c){let a=ov(cp).clients||[];return !a.length||a.some(x=>c.includes(x)||x.includes(c))}function eligible(cp,r){if(!allowed(cp,r.client)||r.month<cp.sm||r.month>cp.em)return false;if(cp.mg1.length&&!cp.mg1.some(x=>s(x)===s(r.brandName)))return false;let ex=new Set([...(cp.exclude||[]),...(ov(cp).exclude||[])]);return !ex.has(r.sku)}
function buckets(cp){let rr=rate(cp);if(!rr)return[];let m=new Map();for(let r of D.so){if(!eligible(cp,r))continue;let k=[r.client,r.code,r.month,r.channel,r.sku].join('|'),z=m.get(k)||{...r,so:0,rate:rr};z.so+=r.so;m.set(k,z)}let a=[...m.values()].map(x=>({...x,so:Math.max(0,x.so),gross:Math.max(0,x.so)*rr,occ:0}));for(let t of D.tts.filter(x=>x.cp===cp.id)){let mo=ym(t.start),cand=a.filter(x=>x.client===t.client&&(!t.code||x.code===t.code)&&(!mo||x.month===mo)&&(!t.sku||x.sku===t.sku));if(!cand.length)cand=a.filter(x=>x.client===t.client&&(!mo||x.month===mo));let w=cand.reduce((q,x)=>q+x.gross,0);cand.forEach(x=>x.occ+=t.amount*(w?x.gross/w:1/cand.length))}a.forEach(x=>x.net=Math.max(0,x.gross-x.occ));return a}
function selectCP(id){state.cp=id;render()}function saveOverride(){if(!state.cp)return;state.ov[state.cp]={rate:n(rateOverride.value),clients:list(clientOverride.value),exclude:list(excludeOverride.value)};render()}function setApproved(c,v){state.approved[state.cp+'|'+c]=n(v);renderCap();renderPlanClients();saveState()}
function render(){renderCP();renderCap();renderPlanClients();renderPlans();kSO.textContent=D.so.length;kTTS.textContent=D.tts.length;kCP.textContent=D.cps.length;kSKU.textContent=D.catalog.size;saveState()}
function renderCP(){let opts=D.cps.map(x=>`<option value="${x.id}">${x.id}｜${x.name}</option>`).join('');[cpSel,capSel,planCP].forEach(e=>{e.innerHTML=opts;e.value=state.cp});cpRows.innerHTML=D.cps.map(x=>`<tr><td class="mono">${x.id}</td><td>${x.name}</td><td>${x.start} ~ ${x.end}</td><td class="num">${money(x.budget)}</td><td>${rate(x)?pct(rate(x)):'<span class="badge warn">待确认</span>'}</td><td>${x.mg1.join(' / ')}</td><td>${x.rates.length>1?'多费率 ':''}${x.exclude.length?'排除SKU '+x.exclude.join(','):''}</td></tr>`).join('');let cp=D.cps.find(x=>x.id===state.cp);if(cp){let o=ov(cp);rateOverride.value=o.rate||'';clientOverride.value=(o.clients||[]).join(',');excludeOverride.value=(o.exclude||[]).join(',')}}
function renderCap(){let cp=D.cps.find(x=>x.id===state.cp);if(!cp){clientRows.innerHTML=bucketRows.innerHTML='';return}let b=buckets(cp),hm={},om={};b.forEach(x=>hm[x.client]=(hm[x.client]||0)+x.net);D.tts.filter(x=>x.cp===cp.id).forEach(x=>om[x.client]=(om[x.client]||0)+x.amount);clientRows.innerHTML=Object.keys(hm).sort((a,z)=>hm[z]-hm[a]).map(c=>`<tr><td>${c}</td><td class="num">${money(hm[c])}</td><td class="num">${money(om[c]||0)}</td><td class="num"><input class="edit" type="number" step="0.01" value="${state.approved[cp.id+'|'+c]||''}" onchange="setApproved('${c.replaceAll("'","\\'")}',this.value)"></td></tr>`).join('');let mp=n(minPit.value)||500;bucketRows.innerHTML=b.sort((a,z)=>a.client.localeCompare(z.client)||z.month.localeCompare(a.month)).map(x=>`<tr><td>${x.client}</td><td class="mono">${x.code}</td><td>${x.month}</td><td>${x.channel}</td><td class="mono">${x.sku}</td><td class="num">${money(x.so)}</td><td class="num">${pct(x.rate)}</td><td class="num">${x.net<mp?'<span class="badge warn">'+money(x.net)+'</span>':money(x.net)}</td></tr>`).join('')}
function renderPlanClients(){let cp=D.cps.find(x=>x.id===state.cp);if(!cp){planClient.innerHTML='';return}let cs=[...new Set(buckets(cp).map(x=>x.client))],old=planClient.value;planClient.innerHTML=cs.map(c=>`<option>${c}</option>`).join('');if(cs.includes(old))planClient.value=old;let a=state.approved[cp.id+'|'+planClient.value];if(a)planAmt.value=a}
function rd(v,u){return Math.floor((v+1e-9)/u)*u}function makePlan(){let cp=D.cps.find(x=>x.id===state.cp),c=planClient.value,target=Math.min(n(planAmt.value),cp?.budget||0);if(!cp||!c||!target)return alert('请补齐CP、客户和金额');let mp=n(minPit.value)||500,u=n(roundUnit.value)||100,a=buckets(cp).filter(x=>x.client===c&&x.net>0);if(histS.value)a=a.filter(x=>x.month>=histS.value);if(histE.value)a=a.filter(x=>x.month<=histE.value);a.sort((x,z)=>z.month.localeCompare(x.month)||z.net-x.net);state.plans=state.plans.filter(x=>!(x.cp===cp.id&&x.client===c));let left=target;for(let x of a){if(left<=.005)break;if(x.net<mp&&left>mp)continue;let v=Math.min(left,x.net),tail=left<=x.net+.005,use=tail?v:rd(v,u);if(use<mp&&!tail)continue;if(use<=0)continue;state.plans.push({...x,cp:cp.id,amount:+use.toFixed(2),rs:x.month.slice(0,4)+'-'+x.month.slice(4)+'-01',re:mend(x.month),ss:sysS.value,se:sysE.value});left-=use}if(left>.005&&/^\d{6}$/.test(futureM.value)){let base=a[0]||D.so.find(x=>x.client===c);if(base)state.plans.push({...base,cp:cp.id,month:futureM.value,rate:rate(cp),amount:+left.toFixed(2),rs:'',re:'',ss:sysS.value,se:sysE.value,net:0,gross:0,occ:0})}renderPlans();renderOut();saveState()}
function renderPlans(){planRows.innerHTML=state.plans.map((x,i)=>`<tr><td class="mono">${x.cp}</td><td>${x.client}</td><td class="mono">${x.code}</td><td>${x.month}</td><td>${x.channel}</td><td class="mono">${x.sku}</td><td class="num">${pct(x.rate)}</td><td class="num">${money(x.amount)}</td><td>${x.rs?x.rs+'~'+x.re:''}</td><td><button class="btn" onclick="state.plans.splice(${i},1);renderPlans();renderOut()">删</button></td></tr>`).join('');renderOut()}
const H=['City','CityName','CityGroup','CityGroupName','Region','RegionName','Distributor Code','Distributor Name','SubDistributor Code','SubDistributor Name','Channel','ChannelName','AC Code','AC Name','Number of Store','Store Code','Store Name','TPC Code','Business Name','Business Code','MG1','MG1 Description','Product Code','Product Description','Product Remark','NPS Price','Activity Code in Cycle Plan','Activity Description','Pre-evaluation Code','Promotion Start Date','Promotion End Date','Promotion Days','Month','Year','Price/Case','Order Qty','Order Amount','Disc.Rate','Allowed Discount','DM Fee','Tax Rate','Tax Value','Total Budget','Remarks','RemarkStartDate','RemarkEndDate'];
function outRow(p){let cp=D.cps.find(x=>x.id===p.cp)||{},cat=D.catalog.get(p.sku)||{},prof=D.profiles.get(p.code)||{},nps=n(cat.nps),amt=n(p.amount),ord=p.rate?amt/p.rate:0,qty=nps?ord/nps:0,city=prof.city||'';return [ '',city,'', '', '', '',p.code,p.name||prof.name||p.client,'','', '',p.channel,'','', '', '', '', '', 'Dairy','CNA',p.brand||'',p.brandName||'',p.sku,cat.name||p.skuName||'','包装规格及NPS箱价一致的产品也可参加',nps,cp.id,cp.name,'',p.ss,p.se,days(p.ss,p.se),+p.ss.slice(5,7),+p.ss.slice(0,4),nps,qty,ord,p.rate,amt,0,0,0,amt,cp.mechanism,p.rs,p.re]}
function days(a,b){let x=date(a),y=date(b);return x&&y?Math.round((y-x)/86400000)+1:0}function renderOut(){let sums={};state.plans.forEach(x=>sums[x.cp]=(sums[x.cp]||0)+x.amount);let warns=[];Object.entries(sums).forEach(([id,v])=>{let cp=D.cps.find(x=>x.id===id);if(cp&&v>cp.budget+.005)warns.push(id+'超CP余额')});outMsg.className='msg '+(warns.length?'warn':'ok');outMsg.textContent=warns.length?warns.join('；'):(state.plans.length?'金额校验通过。':'先生成计划。');outRows.innerHTML=state.plans.map(p=>{let r=outRow(p);return `<tr><td>${r[6]} ${r[7]}</td><td>${r[11]}</td><td class="mono">${r[22]}</td><td>包装规格及NPS箱价一致的产品也可参加</td><td class="mono">${r[26]}</td><td>${r[29]}~${r[30]}</td><td class="num">${n(r[25]).toFixed(2)}</td><td class="num">${n(r[35]).toFixed(4)}</td><td class="num">${money(r[42])}</td><td>${r[44]?r[44]+'~'+r[45]:''}</td></tr>`}).join('')}
function downloadExcel(){if(!state.plans.length)return alert('没有计划');if(typeof XLSX==='undefined')return alert('Excel解析组件未加载');let data=[['促销计划-价格折扣'],[],H,H,...state.plans.map(outRow)],ws=XLSX.utils.aoa_to_sheet(data);ws['!cols']=H.map((x,i)=>({wch:[7,8,8,10,8,10,14,28,14,20,8,24,10,20,10,12,18,12,14,12,10,22,14,34,34,12,22,28,18,14,14,12,8,8,12,12,14,10,14,10,10,10,14,35,14,14][i]||12}));let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'促销计划-价格折扣');XLSX.writeFile(wb,'促销计划-价格折扣_费用规划助手.xlsx')}
function copyTSV(){let t=[H,...state.plans.map(outRow)].map(r=>r.join('\t')).join('\n');navigator.clipboard.writeText(t).then(()=>alert('已复制'))}
function saveState(){localStorage.setItem('expense-planner-public',JSON.stringify(state))}function loadState(){try{state={...state,...JSON.parse(localStorage.getItem('expense-planner-public')||'{}')}catch(e){}}
function resetAll(){localStorage.removeItem('expense-planner-public');location.reload()}
init();render();